---

- name: Install Filebeat
  hosts: web_servers
  become: yes

  tasks:
  - name: Get Filebeat
    ansible.builtin.get_url:
      url: https://mirror.yandex.ru/mirrors/elastic/7/pool/main/f/filebeat/filebeat-7.17.9-amd64.deb
      dest: /home/znak/

  - name: Install Filebeat
    apt:
      deb: /home/znak/filebeat-7.17.9-amd64.deb

  - name: Systemctl daemon reload
    systemd:
      daemon_reload: true
      name: filebeat.service
      state: started

  - name: Copy conf-file
    copy:
      src: ./files/filebeat.yml
      dest: /etc/filebeat/filebeat.yml
      mode: 0644
      owner: root
      group: root

  - name: Restart Filebeat
    systemd:
      name: filebeat.service
      state: restarted