---

- name: Install Kibana
  hosts: kibana_server
  become: yes

  tasks:
  - name: Get Kibana
    ansible.builtin.get_url:
      url: https://mirror.yandex.ru/mirrors/elastic/7/pool/main/k/kibana/kibana-7.17.9-amd64.deb
      dest: /home/znak/

  - name: Install Kibana
    apt:
      deb: /home/znak/kibana-7.17.9-amd64.deb

  - name: Systemctl daemon reload
    systemd:
      daemon_reload: true
      name: kibana.service
      state: started

  - name: Copy conf-file
    copy:
      src: ./files/kibana.yml
      dest: /etc/kibana/kibana.yml
      mode: 0644
      owner: root
      group: kibana

  - name: Restart Kibana
    systemd:
      name: kibana.service
      state: restarted